# Generated by Django 5.0.7 on 2025-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_can_create_clubs_user_can_create_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for login (optional)",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
    ]
