# Generated by Django 5.0.7 on 2025-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address (optional)",
                max_length=254,
                null=True,
            ),
        ),
    ]
