# Generated by Django 5.0.7 on 2025-10-25 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = []
