# Generated by Django 5.0.7 on 2025-10-25 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_make_email_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Student ID number", max_length=20, unique=True
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                (
                    "year_of_study",
                    models.CharField(
                        choices=[
                            ("1st", "1st Year"),
                            ("2nd", "2nd Year"),
                            ("3rd", "3rd Year"),
                            ("4th", "4th Year"),
                            ("5th", "5th Year"),
                            ("graduate", "Graduate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Why do you need an account?")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
