# Generated by Django 5.0.7 on 2025-10-25 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_accountrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
