# Generated by Django 5.0.7 on 2025-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionrequest",
            name="event_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="event_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="event_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="event_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="event_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
