# Generated by Django 5.0.7 on 2025-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_permissionrequest_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionrequest",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images"),
        ),
    ]
