services:
  - type: web
    name: smart-campus
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "smart-campus.onrender.com,localhost,127.0.0.1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smart-campus-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: smart-campus-db
    plan: starter
    region: oregon
