# Generated by Django 5.0.7 on 2025-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_found_images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("found", "Found"),
                            ("claimed", "Claimed"),
                        ],
                        default="lost",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
