# Generated by Django 5.0.7 on 2025-10-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="club_members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="president",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_president",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
